/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'bat_karo';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String CHATX_APP_CB38F_FIREBASE_ADMINSDK_610VW_0A7E258777 = 'assets/chatx-app-cb38f-firebase-adminsdk-610vw-0a7e258777.json';
}
